name: Build APK

on:
  push:
    branches:
      - main  # اگر شاخه‌ات main نیست، تغییر بده

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the APK
        uses: ractoc/buildozer-action@v1.1.5
        with:
          command: buildozer android debug
