name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Accept Android SDK licenses
        run: |
          echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" > local.properties
          yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          buildozer android debug
