name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk libffi-dev libssl-dev libsqlite3-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android SDK licenses manually for Buildozer
        run: |
          mkdir -p ~/.android
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg || true

      - name: Initialize Buildozer (only if .spec file doesn't exist)
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-apk
          path: bin/*.apk
