[app]

title = Calculator
package.name = calculator
package.domain = org.kivy
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait
osx.kivy_version = 2.1.0

fullscreen = 1

[buildozer]

log_level = 2
warn_on_root = 1

# مسیر SDK اندروید
android.sdk_path = /home/runner/.buildozer/android/platform/android-sdk

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
android.ndk_path = 

# (str) Android entry point, default is ok
android.entrypoint = org.kivy.android.PythonActivity

# (str) Android app theme, default is 'import android' (crashes with newer toolchains)
# android.theme = '@android:style/Theme.NoTitleBar'

# (bool) Use --private data storage (True) or --dir public storage (False)
android.private_storage = True

# (str) Android NDK version to use (this is optional)
android.ndk = 25b

# (bool) Use --bootstrap=webview to use the kivy-ios WebView
# ios.use_webview = False

# (list) Permissions
android.permissions = INTERNET

# (str) Supported orientation (one of landscape, sensorLandscape, portrait or all)
orientation = portrait

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (bool) Hide the statusbar
android.hide_statusbar = 0

# (str) Application icon
# icon.filename = %(source.dir)s/icon.png

# (list) Supported Android architectures
android.archs = armeabi-v7a, arm64-v8a

# (str) Android API to use
android.api = 31

# (str) Minimum API your APK will support
android.minapi = 21

# (str) Android SDK version to use
android.sdk = 26

# (str) Extra command line arguments to pass when starting the application
# android.extra_args = 

# (bool) Copy library instead of making a libpymodules.so
copy_libs = 1
